name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'src/**'
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate fire severity analysis
      run: |
        python src/process_aoi.py data/dummy_aoi.geojson
        
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Copy generated files
      run: |
        mkdir -p docs/outputs
        cp ../docs/outputs/fire_severity_map.html docs/outputs/ || echo "No map file to copy"
        cp ../docs/outputs/fire_severity.tif docs/outputs/ || echo "No raster file to copy"
        
    - name: Commit and push to gh-pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/outputs/
        git diff --quiet && git diff --staged --quiet || git commit -m "auto: update fire severity analysis artifacts"
        git push origin gh-pages 