name: 🔥 Manual - Generate dNBR Job

on:
  workflow_dispatch:
    inputs:
      fire_id:
        description: 'Fire ID to process'
        required: true
        default: 'fire_001'
      force_reprocess:
        description: 'Force reprocessing even if exists'
        required: false
        default: false
        type: boolean

jobs:
  submit-gee-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history for commit hash
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up GEE authentication
      run: |
        python -c "from src.gee_jobs import setup_gee_authentication; setup_gee_authentication()"
        
    - name: Verify GEE connection
      run: |
        python -c "from src.gee_jobs import verify_gee_connection; verify_gee_connection()"
        
    - name: Generate dNBR analysis
      id: generate
      run: |
        # Get generator type from GitHub variables
        GENERATOR_TYPE="${{ vars.DNBR_GENERATOR_TYPE || 'dummy' }}"
        
        # Generate dNBR analysis and capture analysis ID
        analysis_id=$(python scripts/generate_dnbr.py data/fire.geojson $GENERATOR_TYPE | grep "Analysis ID:" | cut -d' ' -f3)
        
        # Output analysis ID for next action
        echo "analysis_id=$analysis_id" >> $GITHUB_OUTPUT
        echo "generator_type=$GENERATOR_TYPE" >> $GITHUB_OUTPUT
        
        echo "✅ dNBR analysis generated: $analysis_id"
        echo "🔧 Generator type: $GENERATOR_TYPE"
        
    - name: Set up AWS credentials (noop)
      run: |
        echo "🔗 AWS credentials setup (noop)"
        echo "   Would configure AWS credentials for S3 access"
        
    - name: Show job summary
      run: |
        echo "🎯 GEE Job Summary:"
        echo "   Fire ID: ${{ github.event.inputs.fire_id }}"
        echo "   Force reprocess: ${{ github.event.inputs.force_reprocess }}"
        echo "   Job tracking: S3 bucket fire-severity-sa-jobs"
        echo ""
        echo "📋 Next steps:"
        echo "   1. Check job status with: python -c \"from src.gee_jobs import list_pending_jobs; print(list_pending_jobs())\""
        echo "   2. Run check-gee-results workflow when ready to download" 