name: Generate Pages Content

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'src/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate fire severity analysis
      run: |
        python src/process_aoi.py data/dummy_aoi.geojson
        
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/outputs/
        git diff --quiet && git diff --staged --quiet || git commit -m "auto: regenerate fire severity analysis and map"
        git push 