name: Generate Pages Content

on:
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'src/**'
      - '.github/workflows/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests with coverage
      run: |
        python -m pytest tests/ -v --cov=src --cov-branch --cov-report=xml --cov-report=term-missing
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  generate-content:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Sync with main branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch origin main
        git reset --hard origin/main
    
    - name: Remove .gitignore rules for outputs (gh-pages only)
      run: |
        # Remove the line that excludes docs/outputs/ files
        # This allows outputs to be committed on gh-pages branch
        sed -i '/^docs\/outputs\/\*$/d' .gitignore
        # Add a comment to indicate this is for gh-pages
        echo "# gh-pages: outputs are allowed to be committed" >> .gitignore
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Generate fire severity analysis
      run: |
        # Create the outputs directory
        mkdir -p docs/outputs/
        python __main__.py data/fire.geojson
        
    - name: Commit generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/outputs/
        git diff --quiet && git diff --staged --quiet || git commit -m "auto: regenerate fire severity analysis and map"
        git push origin gh-pages --force 